### ISSUE TITLE
repo tooling: pnpm install can be a total silent no-op (exit 0, no node_modules) when crates/brink-web/www/pkg is missing — distinct from the #2479 symptom

### ISSUE THREAD

**Issue by Syynth** [Syynth/brink#2593]
Follow-up from PR #2582's build comment (delivering #2580), w160.

## The gap

#2479 (fixed by #2492) covers a *silently-unresolved link* after an install that otherwise looks successful. This is a different variant, found in a fresh worktree with no `crates/brink-web/www/pkg`:

`pnpm install` printed `ERR_PNPM_LINKED_PKG_DIR_NOT_FOUND` for `packages/wasm` and **exited 0 with no `node_modules` written at all** — a total no-op install, not a partial/silently-unresolved link. The next command then failed with a bare `vitest: not found`, which reads as a missing binary rather than a skipped install.

`pnpm run check:wasm-pkg` (added by #2492) diagnoses it once you think to run it, but nothing forces that step before install in this failure shape.

## Ask

Cover this specific failure mode: either make `check:wasm-pkg` (or an equivalent pre-install check) run automatically ahead of `pnpm install` in the documented cloud-session flow, or make the total-no-op-install case fail loudly (non-zero exit) instead of silently producing no `node_modules`.

## References

- #2479 / PR #2492 (fixed the silently-unresolved-link variant; this is a different variant of the same root cause)
- #2580 / PR #2582 (where this was found, out of that PR's fence)
- `scripts/setup-dev.sh`, `pnpm run check:wasm-pkg`
- CLAUDE.md "Cloud / fresh-environment sessions"

**Comment by Syynth** [comment]
Scope discovered beyond this fence: **`main` is currently red on the `frontend` gate, from a duplicate method in the studio's `brink-web` mock — unrelated to this issue, and deliberately not fixed in PR #2596.**

`packages/brink-studio/src/__mocks__/brink-web.ts` declares `resolve_code_action_doc` **twice**:

- **line 1043** — added by #2583 (refusal-shape parity), delegates to `resolveCodeActionImpl`, returns `structuralRefusal("unknown document handle")`.
- **line 1476** — added by #2578/#2585 (code-actions apply reachability), unconditionally returns a refusal, `structuralRefusal("unknown handle")`.

Two sibling PRs in the same wave each added the same method to the same mock in different regions of the file, so git merged both without a conflict.

**Two failures, one root cause:**

1. `pnpm --filter @brink-lang/studio typecheck` → `error TS2393: Duplicate function implementation.` at both lines (exit 2).
2. `pnpm --filter @brink-lang/studio test` → `src/__tests__/structural-refusal-shape.test.ts > mock refusal payloads match the Rust structs (#2568) > resolve_code_action_doc (unknown document handle) answers a full StructuralResult` — `AssertionError: expected { ok: false, …(4) } to deeply equal { cross_file_edits: [], …(4) }`. 1153/1154 tests pass; this is the only failure.

The subtle part worth flagging: in JS class semantics the **later declaration wins at runtime**, so #2583's real delegating implementation is **silently shadowed** — the mock always returns the line-1476 refusal. #2583's refusal-parity coverage is therefore asserting against an implementation that is no longer reachable. That is the same class of problem as the wave's own new "mock parity" house rule, arriving from the opposite direction: not a fabricated payload, but a real payload made unreachable by a merge.

Proven pre-existing, not introduced by #2596: that file is byte-identical to `origin/main` (`git hash-object` == `git rev-parse origin/main:…` == `9e58101550a0bb920ce776d07fb741051a4ee777`), and #2596's diff contains zero TypeScript files.

Also worth a separate look, surfaced while reproducing here: **pnpm is pinned only to a floating major** (`corepack prepare pnpm@10` in `scripts/setup-dev.sh`, `pnpm/action-setup version: 10` in `ci.yml`; no `packageManager` field in the root `package.json`). This family (#2479 / #2531 / #2593) keeps recurring partly because the install's failure behaviour differs across 10.x — on 10.34.5 the missing-pkg install exits `1` with a new `ERR_PNPM_LINKED_PKG_DIR_NOT_FOUND` code, where #2492 recorded exit `0` with a raw `ENOENT … scandir`. Pinning an exact pnpm version would make that behaviour reproducible instead of ambient. #2596 works around it by never trusting the exit code, but the pin itself is out of its fence.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by Syynth** [comment]
Retro true-up (w160): **not merged yet — leaving this open.**

PR #2596 (`auto/issue-2593`) is `state: open`, `merged: false`, `mergeable_state: blocked` as of this check. It was armed for auto-merge but blocked on the pre-existing `main` breakage (duplicate `resolve_code_action_doc` in `packages/brink-studio/src/__mocks__/brink-web.ts`, tracked by #2600, repaired by #2599 which merged at 10:41 UTC). #2596's checks were re-queued against the fixed `main` moments ago and are still running (`Test`, `Static checks`, `Desktop smoke` in progress; `Frontend (brink-studio)`, E2E, etc. queued) — none have completed. This is genuinely "waiting on required checks," not a review park or a conflict. **Flagging for the next wave to re-verify** whether it actually lands.

Discovered-scope follow-ups from #2596's build/review, filed rather than left implicit:
- #2604 — pnpm pinned only to a floating major; root cause of this whole install-failure family
- #2605 — `npm-release.yml` has no post-install verification; no-op-into-stale-tree not detected; Windows `spawnSync` portability
- #2606 — `docs/publishing.md`, the book's studio doc, and `.claude/skills/autonomous-pump/BRINK-CONFIG.md` still document the unguarded `pnpm install --frozen-lockfile` PR #2596 was meant to retire

The pre-existing `main` breakage itself is #2600/#2599, not this issue's remainder — noted here only because it's why #2596 is still blocked.

---
_Generated by [Claude Code](https://claude.ai/code)_
