### ISSUE TITLE
Two PRs green individually can land a red main: nothing evaluates the merge result

### ISSUE THREAD

**Issue by Syynth** [Syynth/brink#2600]
## What happened (2026-08-16)

`main` went red on `Frontend (brink-studio)` and stayed red, taking every open PR with it:

```
src/__mocks__/brink-web.ts(1043,3): error TS2393: Duplicate function implementation.
src/__mocks__/brink-web.ts(1476,3): error TS2393: Duplicate function implementation.
```

Two PRs each added a `resolve_code_action_doc` method to `EditorSession` in `packages/brink-studio/src/__mocks__/brink-web.ts`:

- #2583 (`d707f2f23`) added it at line 1043
- #2585 (`b4c053fb1`) added it at line 1476

**Both were green when merged.** Each was tested against a `main` that did not yet contain the other, so no CI run ever evaluated the combination. The conflict is not a textual merge conflict — git merged both cleanly, into adjacent-but-distinct regions of one file — so nothing flagged it at merge time either.

Repaired in #2599, which also adds a guard against this specific shape (a method defined twice in one class in that file).

## Why it is worth a process decision, not just a fix

The guard in #2599 closes *this* file and *this* shape. The general hazard is untouched: any two PRs whose combination is worse than either part will land the same way. This one happened to be loud (`tsc` caught it); a semantic version — two PRs that each satisfy an invariant only because the other's change is absent — would land silently.

Note that the shadowing was also **not** just a build error. The later definition won, so the faithful implementation became dead code and the mock's doc-handle op could never succeed. That is a mock-fidelity regression of exactly the class #2568/#2577 exist to prevent, and it was live on `main` for the window.

## Options — this is a maintainer call

**(a) Require branches to be up to date before merging** (branch protection). Guarantees CI evaluates the actual merge result. Cost: serializes the merge train and re-runs the full matrix per landing, which on this repo is not cheap (E2E ×4, Test all-features, Desktop smoke, wasm). With several PRs landing per wave this is the dominant cost.

**(b) Use a merge queue.** Same guarantee, batched — GitHub tests the queued combination rather than each PR against a moving `main`. More setup; changes how auto-merge behaves.

**(c) Update-and-verify only for PRs that touch a shared file.** Cheaper, but needs a definition of "shared" and is easy to get wrong.

**(d) Accept it and repair forward.** Defensible if the rate stays this low — this is the first instance I know of — given the CI cost of (a)/(b).

I have no basis to pick between these; the tradeoff is CI minutes against a rare-but-total outage, and only the maintainer can weigh that.

## The contributing factor I *can* fix

The wave that produced both PRs assigned `__mocks__/brink-web.ts` to #2577 exclusively. #2578 added a method to it anyway, during a review round — file ownership was stated up front but not re-checked when a review round widened the diff. That is mine to tighten and does not need a ruling.
